import { describe, it, expect } from "vitest";
import { forge } from "@/data/mindforge";

/**
 * The snapshot is generated by an export script in the mindforge repo, so these
 * assert the file is well formed rather than that it holds any given mission.
 * A bad export should fail here, not on the page.
 */
describe("mindforge snapshot", () => {
  it("carries an ISO snapshot date", () => {
    expect(forge.snapshotAt).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it("has no duplicate topics, which the list keys on", () => {
    const topics = forge.missions.map((m) => m.topic);
    expect(new Set(topics).size).toBe(topics.length);
  });

  it("keeps no em-dashes in topics or module names", () => {
    for (const missionEntry of forge.missions) {
      expect(missionEntry.topic).not.toMatch(/[—–]/);
      for (const entry of missionEntry.modules) {
        expect(entry.name, missionEntry.topic).not.toMatch(/[—–]/);
      }
    }
  });

  it("carries only missions I have actually started", () => {
    // The export filters these out. A curriculum with nothing finished is an
    // intention, and the page is about work rather than about ambition.
    for (const missionEntry of forge.missions) {
      expect(missionEntry.completed, missionEntry.topic).toBeGreaterThan(0);
    }
  });

  it("never completes more lessons than it planned", () => {
    for (const missionEntry of forge.missions) {
      expect(missionEntry.completed).toBeLessThanOrEqual(missionEntry.total);
      for (const entry of missionEntry.modules) {
        if (entry.completed === null || entry.total === null) continue;
        expect(entry.completed, entry.name).toBeLessThanOrEqual(entry.total);
      }
    }
  });

  it("adds each mission's fraction up from its own modules", () => {
    for (const missionEntry of forge.missions) {
      const planned = missionEntry.modules.filter((m) => m.total !== null);
      const completed = planned.reduce((sum, m) => sum + (m.completed ?? 0), 0);
      const total = planned.reduce((sum, m) => sum + (m.total ?? 0), 0);

      expect(completed, missionEntry.topic).toBe(missionEntry.completed);
      expect(total, missionEntry.topic).toBe(missionEntry.total);
    }
  });
});
