// Generated by `pnpm --filter @mindforge/db export:portfolio` in the
// mindforge repo. Do not edit by hand: the next export overwrites it.
//
// A snapshot, not a feed. Mindforge runs locally, so these numbers are as fresh
// as the last commit, and a plan that gains or loses lessons shows up here as a
// diff rather than silently rewriting a public page.
import type { ForgeSnapshot } from "@/types/forge";

export const forge: ForgeSnapshot = {
  snapshotAt: "2026-09-13",
  missions: [
    {
      topic: "System design, for real systems and for interviews",
      completed: 3,
      total: 68,
      modules: [
        { name: "Turning a prompt into requirements", completed: 3, total: 4 },
        { name: "Estimation and latency", completed: 0, total: 4 },
        { name: "What one machine can do", completed: 0, total: 5 },
        { name: "How databases actually store things", completed: 0, total: 6 },
        { name: "Caching", completed: 0, total: 5 },
        { name: "Scaling out", completed: 0, total: 5 },
        { name: "Replication", completed: 0, total: 5 },
        { name: "Queues and event streams", completed: 0, total: 5 },
        { name: "Partitioning and sharding", completed: 0, total: 5 },
        { name: "Consistency and consensus", completed: 0, total: 5 },
        { name: "Designing the interface", completed: 0, total: 4 },
        { name: "Reliability, observability and cost", completed: 0, total: 5 },
        { name: "Designing a system from scratch", completed: 0, total: 5 },
        { name: "The interview itself", completed: 0, total: 5 },
      ],
    },
    {
      topic: "Personal finances and investing in Brazil",
      completed: 2,
      total: 68,
      modules: [
        { name: "Your reserve number", completed: 2, total: 5 },
        { name: "Reading Brazilian rates", completed: 0, total: 5 },
        { name: "Where your money is", completed: 0, total: 4 },
        { name: "Tax on fixed income", completed: 0, total: 5 },
        { name: "Homes for a reserve", completed: 0, total: 6 },
        { name: "Actually doing it", completed: 0, total: 5 },
        { name: "The monthly number", completed: 0, total: 5 },
        { name: "Funding a dated expense", completed: 0, total: 5 },
        { name: "Getting money out of the PJ", completed: 0, total: 5 },
        { name: "Real versus nominal", completed: 0, total: 4 },
        { name: "Honest measurement", completed: 0, total: 4 },
        { name: "Past the reserve", completed: 0, total: 5 },
        { name: "Your own allocation", completed: 0, total: 5 },
        { name: "The quarterly pass", completed: 0, total: 5 },
      ],
    },
  ],
};
